<?php

/**
 * @file
 * Contains module hooks.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function ivw_integration_theme() {
  return [
    'ivw_call' => [
      'variables' => [
        'st' => NULL,
        'cp' => NULL,
        'sv' => NULL,
        'co' => NULL,
        'dn' => NULL,
        'dc' => NULL,
        'dg' => NULL,
        'pt' => NULL,
        'bfe' => NULL,
        'legacy_mode' => NULL,
        'mobile_st' => NULL,
        'mobile_cp' => NULL,
        'mobile_sv' => NULL,
        'mobile_dn' => NULL,
        'mobile_width' => NULL,
        'defer' => FALSE,
      ],
      'template' => 'ivw-call',
    ],
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function ivw_integration_form_node_form_alter(&$form, FormStateInterface $form_state) {
  /* Is there a better way to get the node? */
  $entity = $form_state->getBuildInfo()['callback_object']->getEntity();
  $has_settings = FALSE;

  /*
   * Set group of all ivw_integration_settings elements
   */
  foreach ($entity->getFieldDefinitions() as $fieldDefinition) {
    if ($fieldDefinition->getType() === 'ivw_integration_settings') {
      $has_settings = TRUE;
      $form[$fieldDefinition->getName()]['#group'] = 'ivw_integration_settings_override';
    }
  }
  if ($has_settings) {
    if (empty($form['advanced'])) {
      $form['advanced'] = [
        '#type' => 'vertical_tabs',
        '#attributes' => ['class' => ['entity-meta']],
        '#weight' => 99,
      ];
    }
    $form['ivw_integration_settings_override'] = [
      '#type' => 'details',
      '#title' => t('IVW settings'),
      '#open' => FALSE,
      '#group' => 'advanced',
      '#optional' => TRUE,
    ];

  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function ivw_integration_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state) {
  ivw_integration_form_node_form_alter($form, $form_state);
}

/**
 * Implements hook_page_attachments().
 */
function ivw_integration_page_attachments(array &$page) {
  $trackerService = \Drupal::service('ivw_integration.tracker');
  $tracker = $trackerService->getTrackingInformation();

  // Site value is missing, do not render tag.
  if (empty($tracker['st'])) {
    return;
  }

  if (!$trackerService->isLanguageEnabled()) {
    return;
  }

  $page['#cache']['tags'] = Cache::mergeTags($page['#cache']['tags'] ?? [], $trackerService->getCacheTags());

  if ($tracker['legacy_mode']) {
    $html_head_item = &$page['#attached']['html_head'][];
    $html_head_item = [
      [
        '#tag' => 'script',
        '#attributes' => [
          'src' => 'https://script.ioam.de/iam.js' . (\Drupal::config('system.performance')->get('js.preprocess') ? '?m=1' : ''),
        ],
      ],
      'ivw_library',
    ];
    $defer_script = \Drupal::config('ivw_integration.settings')->get('defer');
    if ($defer_script) {
      $html_head_item[0]['#attributes']['defer'] = 'defer';
    }
    $page['#attached']['library'][] = 'ivw_integration/ivw_call';
  }

  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'link',
      '#attributes' => [
        'rel' => 'preload',
        'href' => '//' . $tracker['dn'] . '/iomm/latest/manager/base/es6/bundle.js',
        'as' => 'script',
        'id' => 'IOMmBundle',
      ],
    ],
    'web_manager_base_preload',
  ];

  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'link',
      '#attributes' => [
        'rel' => 'preload',
        'href' => '//' . $tracker['dn'] . '/iomm/latest/bootstrap/loader.js',
        'as' => 'script',
      ],
    ],
    'web_manager_bootstrap_preload',
  ];

  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#attributes' => [
        'src' => '//' . $tracker['dn'] . '/iomm/latest/bootstrap/loader.js',
        'data-cmp-ab' => 2,
      ],
    ],
    'web_manager',
  ];

}
