<?php

use Drupal\node\Entity\Node;

/**
 * Implements hook_update_N().
 *
 * Change maxlength for attachment_path_value (easy email field) to 1024.
 */
function cact_general_update_9005() {
  $database = \Drupal::database();
  $database->query("ALTER TABLE easy_email__attachment_path MODIFY attachment_path_value VARCHAR(1024)");
  $database->query("ALTER TABLE easy_email_revision__attachment_path MODIFY attachment_path_value VARCHAR(1024)");
}
